### ISSUE TITLE
Add series for treemap and bubble chart

### ISSUE THREAD

**Issue by giorgiouboldi** [rawgraphs/rawgraphs-charts#115]
**For which chart are you making a suggestion? **

- Bubble Chart
- Treemap diagram

**Describe your suggestion**
I would add the possibility to add series

**Comment by mikima** [comment]
@giorgiouboldi could you upload a sample dataset for both the models using also series? thanks!

**Comment by giorgiouboldi** [comment]
For the bubble chart try to create a chart for each country. 
X: CO2 emissions (per capita), 
Y: GDP (per capita), 
Connected by: Year

For the treemap you can use the orchestra dataset and use "orchestra type" in series.

[bubblechart-series.tsv.zip](https://github.com/rawgraphs/rawgraphs-charts/files/7769632/bubblechart-series.tsv.zip)

**Comment by mikima** [comment]
@giorgiouboldi working on bubble charts.
We should add an option to use the same scale across series.
We have two options:
- a single options that will use same scale on vertical, horizontal, and size scales
- an option for each one

Do you have preferences?

**Comment by mikima** [comment]
Treemaps (and all the space-filling models) are problematic since they maximise the usage of space, keeping in account space for padding and titles. Dividing them across multiple series of the same area create an issue in finding a way to make them comparable using the same scale.

I have no idea on how to solve it, @uf0 any idea?

**Comment by mikima** [comment]
closed. Series have been added for Bubble Chart.
Treemaps are more complex due problems related to space-filling models, should be reworked in future.
